### ISSUE TITLE
Save option reprompts for name of cafe

### ISSUE THREAD

**Issue by samuel-first** [lucaswhitaker22/bash_cafe#15]
This happens because the [handle_menu() calls new_save()](https://github.com/lucaswhitaker22/bash_cafe/blob/master/scripts/functions/menu_functions.sh#L117), which gets the name of the shop from the player.  It might be better to have the save option use the current name of the cafe and add a 'save as' option to save it under a different name.

On a somewhat related note, as I was looking through the commits, I noticed that there are a lot of commits removing save files.  If you add the line `**/*_saves` to your .gitignore file, that should keep it from pushing them.  You can read more about gitignore [here](https://git-scm.com/docs/gitignore).

**Comment by lucaswhitaker22** [comment]
Thanks for the tip! Fixed up the handle_menu problem.
